export const restaurantTypes = [
  { name: "Fine Dining", icon: "🍽️" },
  { name: "Fast Food", icon: "🍔" },
  { name: "Café & Coffee", icon: "☕" },
  { name: "Pizza Place", icon: "🍕" },
  { name: "Asian Cuisine", icon: "🥢" },
  { name: "Mexican Food", icon: "🌮" },
  { name: "Italian Restaurant", icon: "🍝" },
  { name: "Bakery", icon: "🥖" },
  { name: "Seafood", icon: "🦐" },
  { name: "Steakhouse", icon: "🥩" },
  { name: "Vegetarian", icon: "🥗" },
  { name: "Food Trucks", icon: "🚚" },
  { name: "Breakfast Spot", icon: "🥞" },
  { name: "Ice Cream", icon: "🍦" },
  { name: "Sushi Bar", icon: "🍣" },
  { name: "BBQ Joint", icon: "🍖" },
  { name: "Sandwich Shop", icon: "🥪" },
  { name: "Dessert Shop", icon: "🧁" }
];
